---
Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/Next:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 35
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Exclude:
    - "**/*_spec.rb"

...
