Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Metrics/AbcSize:
  Max: 22

Metrics/LineLength:
  Exclude:
    - spec/gettext_i18n_rails_js/parser/javascript_spec.rb

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
