name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.1
          bundler-cache: true
      - name: Run rubocop
        if: github.event_name != 'push'
        run: bundle exec rubocop
  test_ruby:
    runs-on: ubuntu-latest
    needs: rubocop
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.1, 2.5, 2.7]
        rails: ['3.2', '4.2', '5.2', '6.1']
        exclude:
        # excludes new rails on old ruby
        - rails: '5.2'
          ruby: 2.1
        - rails: '6.1'
          ruby: 2.1
        # excludes old rails on new ruby
        - rails: '3.2'
          ruby: 2.7
        - rails: '4.2'
          ruby: 2.7
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 1.17
          bundler-cache: true
        env:
          RAILS_VERSION: ${{ matrix.rails }}
      - name: Run tests
        run: |
          bundle exec rspec
