---
name: testing

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.1
          bundler: 1.17
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop

  spec:
    runs-on: ubuntu-20.04
    needs: rubocop

    strategy:
      fail-fast: false

      matrix:
        ruby:
          - 2.1
          - 2.5
          - 2.7
        rails:
          - 3.2
          - 4.2
          - 5.2
          - 6.1
        exclude:
          # excludes new rails on old ruby
          - rails: 5.2
            ruby: 2.1
          - rails: 6.1
            ruby: 2.1
          # excludes old rails on new ruby
          - rails: 3.2
            ruby: 2.7
          - rails: 4.2
            ruby: 2.7

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 1.17
          bundler-cache: true
        env:
          RAILS_VERSION: ${{ matrix.rails }}

      - name: Run rspec
        run: bundle exec rspec

...
